### ISSUE TITLE
使用聊天机器人的RestAPI接口，进行检索知识库或其他功能时，通过https请求，返回无授权的报错

### ISSUE THREAD

**Issue by tmaccao** [chatopera/status#1]
![image](https://user-images.githubusercontent.com/33178599/78649965-d046b380-78f0-11ea-8322-d77fc511b085.png)
您好，问题的描述即是标题，具体的详情如上图所示，请问是有哪里需要获取权限吗

**Comment by kylezhang** [comment]
curl 或 postman访问都需要加上 authorization 信息

**Comment by tmaccao** [comment]
您好，请问authorization&nbsp;信息是什么呢，在api文档里好像没有看见。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kyle <notifications@github.com&gt;
发送时间: 2020年4月11日 20:47
收件人: chatopera/status <status@noreply.github.com&gt;
抄送: tmaccao <caoyiming7@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[chatopera/status] 使用聊天机器人的RestAPI接口，进行检索知识库或其他功能时，通过https请求，返回无授权的报错 (#1)

**Comment by Samurais** [comment]
我们提供了不同语言的SDK，以方便大家使用，请问您需要什么语言的SDK？

**Comment by tmaccao** [comment]
可以直接用在线的restapi吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Samurais <notifications@github.com&gt;
发送时间: 2020年4月13日 13:29
收件人: chatopera/status <status@noreply.github.com&gt;
抄送: tmaccao <caoyiming7@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[chatopera/status] 使用聊天机器人的RestAPI接口，进行检索知识库或其他功能时，通过https请求，返回无授权的报错 (#1)

**Comment by Samurais** [comment]
我们已经将RestAPI面向不同语言封装为SDK，参考 https://docs.chatopera.com/products/chatbot-platform/integration.html

**Comment by Samurais** [comment]
如果SDK遇到问题，可以再咨询，如果一定要用RestAPI，可以看SDK的实现，也是在上面链接中。我们不建议直接用RestAPI。
